version: "3.5"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1-1-ubi8
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - data-zk-log:/var/lib/zookeeper/log
      - data-zk-data:/var/lib/zookeeper/data
    networks:
      - confluent
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka-1:
    image: confluentinc/cp-server:7.1.1-1-ubi8
    hostname: kafka-1
    container_name: kafka-1
    networks:
      - confluent
    volumes:
      - data-kafka-1:/var/lib/kafka/data
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: CLIENT://kafka-1:9092,BROKER://kafka-1:9094,CONTROLLER://kafka-1:9095,CLIENT_EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka-1:9092,BROKER://kafka-1:9094,CONTROLLER://kafka-1:9095,CLIENT_EXTERNAL://kafka-1-external:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,CLIENT_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_BROKER_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="kafka" \
        password="kafka-secret" \
        user_kafka="kafka-secret";
      KAFKA_CONTROL_PLANE_LISTENER_NAME: CONTROLLER
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="kafka" \
        password="kafka-secret" \
        user_kafka="kafka-secret";
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"

  kafka-2:
    image: confluentinc/cp-server:7.1.1-1-ubi8
    hostname: kafka-2
    container_name: kafka-2
    networks:
      - confluent
    volumes:
      - data-kafka-2:/var/lib/kafka/data
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: CLIENT://kafka-2:9092,BROKER://kafka-2:9094,CONTROLLER://kafka-2:9095,CLIENT_EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka-2:9092,BROKER://kafka-2:9094,CONTROLLER://kafka-2:9095,CLIENT_EXTERNAL://kafka-2-external:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,CLIENT_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_BROKER_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="kafka" \
        password="kafka-secret" \
        user_kafka="kafka-secret";
      KAFKA_CONTROL_PLANE_LISTENER_NAME: CONTROLLER
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="kafka" \
        password="kafka-secret" \
        user_kafka="kafka-secret";
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"

  kafka-3:
    image: confluentinc/cp-server:7.1.1-1-ubi8
    hostname: kafka-3
    container_name: kafka-3
    networks:
      - confluent
    volumes:
      - data-kafka-3:/var/lib/kafka/data
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: CLIENT://kafka-3:9092,BROKER://kafka-3:9094,CONTROLLER://kafka-3:9095,CLIENT_EXTERNAL://0.0.0.0:39092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka-3:9092,BROKER://kafka-3:9094,CONTROLLER://kafka-3:9095,CLIENT_EXTERNAL://kafka-3-external:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,CLIENT_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_BROKER_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="kafka" \
        password="kafka-secret" \
        user_kafka="kafka-secret";
      KAFKA_CONTROL_PLANE_LISTENER_NAME: CONTROLLER
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="kafka" \
        password="kafka-secret" \
        user_kafka="kafka-secret";
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"

volumes:
  data-zk-log:
  data-zk-data:
  data-kafka-1:
  data-kafka-2:
  data-kafka-3:

networks:
  confluent:
    name: kafka-internal